### ISSUE TITLE
Admin mode: Manage Events

### ISSUE THREAD

**Issue by tayapro** [tayapro/woofspot#4]
As a **admin**, I can **create, edit, and delete events**, so that I can **keep the event calendar up-to-date and correct information**.

### Acceptance criteria:

- [X] New events can be created by providing the event name, description, date, time, location.
- [X] Existing events can be edited to update their details.
- [X] Events that are no longer relevant can be deleted.
