### ISSUE TITLE
Login with Google

### ISSUE THREAD

**Issue by tayapro** [tayapro/woofspot#7]
As a **user**, I want to **sign in using my Google account** so that **I can quickly access the application’s features**.

### Acceptance criteria:

- [X] User can login using a "Sign in with Google" button.
- [X] The user is able to successfully register an account using Google.
- [X] The user's basic profile information (name, email) is automatically populated from their social media profile.

**Comment by tayapro** [comment]
Closed by following commits:
0b86fdb
8c12b38
